#!/bin/bash

SCRIPTDIR=${BASH_SOURCE%/*}

if [ ! -f $SCRIPTDIR/../lib/qq-functions ]; then
    echo "Cannot load libraries"
    exit
else
    . $SCRIPTDIR/../lib/qq-functions
    load_variables
fi

### Main ###=======================================================

exit_if_not_root

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive

log "INSTALL" "Updating system..."
exec_cmd_as "root" "/usr/bin/apt-get update"
log "INSTALL" "Installing dependencies..."
exec_cmd_as "root" "/usr/bin/apt-get -y install git build-essential cmake libboost-dev libmariadb-dev liblua5.1-dev uuid-dev mariadb-server uuid-runtime dnsutils"
exec_cmd_as "root" "sed -i 's/bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf"
exec_cmd_as "root" "grep -q '^[# ]*max_connections' /etc/mysql/mariadb.conf.d/50-server.cnf && sed -i 's/^[# ]*max_connections.*/max_connections = 1000/' /etc/mysql/mariadb.conf.d/50-server.cnf || echo 'max_connections = 1000' >> /etc/mysql/mariadb.conf.d/50-server.cnf"
exec_cmd_as "root" "systemctl restart mariadb && systemctl is-active --quiet mariadb"

log "INSTALL" "Setting up MySQL user..."
exec_cmd_as "root" "$MYSQLBIN <<< \"CREATE DATABASE IF NOT EXISTS $DBNAME\""
mysql_exec_as "root" "DROP USER IF EXISTS '$DBUSER'@'%'; CREATE USER '$DBUSER'@'%' IDENTIFIED BY '$DBPASS'; GRANT ALL ON $DBNAME.* TO '$DBUSER'@'%'"



